CREATE TABLE PATIENT
	(PA_ID	INT NOT NULL PRIMARY KEY,
	PA_LNAME	VARCHAR(20),
	PA_FNAME	VARCHAR(20),
	PA_BLOODTYPE	CHAR(3),
	PA_DOB	DATE,
	AD_ID	INT,
	INS_ID	INT,
	SCRIPT_ID	INT
	);


CREATE TABLE MEDICATION
	(MED_ID INT NOT NULL PRIMARY KEY,
	MED_GENERIC VARCHAR(20) NOT NULL,
	MED_BRAND VARCHAR(20) NOT NULL,
	MED_SHAPE VARCHAR(20) NOT NULL,
	MED_COLOR VARCHAR(20) NOT NULL,
	MED_IMPRINT CHAR(7) NOT NULL
	);

CREATE TABLE PRESCRIPTION
	(SCRIPT_ID INT NOT NULL PRIMARY KEY,
	MED_ID INT NOT NULL,
	PA_ID INT NOT NULL,
	SCRIPT_DOSE VARCHAR(20) NOT NULL,
	SCRIPT_DATE DATE NOT NULL,
	SCRIPT_REFILL INT NOT NULL,
	SCRIPT_REASON VARCHAR(180),
	EMP_ID INT NOT NULL,
	);

CREATE TABLE EMPLOYEE
	(EMP_ID INT NOT NULL PRIMARY KEY,
	EMP_LNAME VARCHAR(20) NOT NULL,
	EMP_FNAME VARCHAR(20) NOT NULL,
	EMP_JOBTYPE VARCHAR(20) NOT NULL,
	EMP_HIREDATE DATE,
	EMP_DOB DATE NOT NULL,
	AD_ID INT NOT NULL
	);

CREATE TABLE DOCTOR
	(EMP_ID INT NOT NULL PRIMARY KEY,
	DOC_DEPT VARCHAR(180),
	DOC_SALARY INT,
	DOC_OFFICE_NUM CHAR(4),
	OFFICE_AD_ID INT
	);

CREATE TABLE NURSE
	(EMP_ID INT NOT NULL PRIMARY KEY,
	UNIT_ID INT,
	NURSE_SHIFT VARCHAR(20),
	NURSE_HOURLY INT,
	NURSE_HRS INT
	);

CREATE TABLE INSURANCE
	(INS_ID INT NOT NULL PRIMARY KEY,
	INS_COMPANY VARCHAR(180) NOT NULL,
	INS_PLAN VARCHAR(20) NOT NULL,
	INS_COPAY INT NOT NULL,
	INS_DEDUCTIBLE INT NOT NULL
	);

CREATE TABLE LAB_WORK
	(LAB_ID INT NOT NULL PRIMARY KEY,
	GLUCOSE VARCHAR(20),
	MONO VARCHAR(20),
	PAP VARCHAR(20),
	STOOL VARCHAR(20),
	URINALYSIS VARCHAR(20)
	);

CREATE TABLE UNIT
	(UNIT_ID INT NOT NULL PRIMARY KEY,
	UNIT_TYPE VARCHAR(180) NOT NULL,
	UNIT_FLOOR CHAR(3) NOT NULL,
	UNIT_SECTION VARCHAR(20)
	);

CREATE TABLE VISIT
	(VISIT_ID INT NOT NULL PRIMARY KEY,
	LAB_ID INT,
	EMP_ID INT NOT NULL,
	PA_ID INT NOT NULL,
	UNIT_ID INT NOT NULL,
	VISIT_DATE DATE NOT NULL,
	VISIT_REASON VARCHAR(180),
	VISIT_DIAG VARCHAR(180)
	);

CREATE TABLE PHARMA_ORDER
	(ORDER_ID INT NOT NULL,
	MED_ID INT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	ORDER_RECEIVED DATE,
	ORDER_SUPPLYBY VARCHAR(180),
	EMP_ID INT NOT NULL,
	CONSTRAINT comp_pk PRIMARY KEY(ORDER_ID,MED_ID)
	);

CREATE TABLE ADDRESS
	(AD_ID INT NOT NULL PRIMARY KEY,
	AD_STREET VARCHAR(60),
	AD_CITY VARCHAR(20),
	AD_STATE CHAR(3),
	AD_ZIP CHAR(5) NOT NULL
	);
